#!/usr/bin/env python3
"""Jev decision generated by prompt2jev from request.json.

One System One request sends every question at once; the code below reads the typed
answers. Every threshold lives in the constants block. The defaults are illustrative:
tune them on labeled data before an answer triggers an action.

Run:
    pip install typesafe-sdk      # the official SDK
    export TYPESAFE_API_KEY=...   # https://console.typesafe.ai/keys
    python3 triage.py             # judges EXAMPLE_STATE
    python3 triage.py state.json  # judges the JSON object in that file; - reads stdin
"""

from __future__ import annotations

import json
import sys

from typesafe_sdk import Choice, Noul, NoulCriteria, TypeSafeClient

MODEL = "jev-latest"  # pin a versioned id such as jev-1.13.0 once thresholds are tuned

# ----- Constants: every threshold in one place -----
CONFIDENCE_FLOOR = 0.5  # a Choice or Score below this is not acted on; a person decides
NOUL_YES = 0.8  # a Noul at or above this counts as yes
NOUL_NO = 0.2  # a Noul at or below this counts as no; in between is uncertain

QUESTIONS = {
    "team": Choice(
        instructions="Which team should handle `ticket.text`?",
        criteria={
            "billing": "Charges, invoices, refunds, or subscriptions.",
            "shipping": "Delivery status, delays, lost or damaged packages.",
            "account": "Login, password, profile, permissions, or security.",
            "other": "None of the listed teams fits, or the message is not a support request.",
        },
    ),
    "urgent": Noul(
        instructions="Does `ticket.text` say the customer cannot use the product or has a deadline today?",
        criteria=NoulCriteria(
            true="States that the product is unusable for them now, or names a same-day deadline.",
            false="Describes a problem they can work around, or sets no deadline.",
        ),
    ),
    "refund_requested": Noul(
        instructions="Does the customer in `ticket.text` explicitly ask for money back or a credit?",
    ),
}

# The state the request was written against. Build the real one from your own data.
EXAMPLE_STATE = {
    "ticket": {
        "text": "Nobody on my team can log in since this morning and payroll closes at 5pm.",
    },
}


def ask(state):
    """Send every question in one request; they run in parallel."""
    with TypeSafeClient() as client:  # reads TYPESAFE_API_KEY; retries 429 and 529 itself
        return client.system_one(state=state, questions=QUESTIONS, model=MODEL)


def read_choice(answer) -> dict:
    """The chosen option, or needs_review when the distribution is too flat to act on."""
    acted = answer.confidence >= CONFIDENCE_FLOOR
    return {"choice": answer.choice if acted else "needs_review", "confidence": answer.confidence,
            "probabilities": answer.probabilities}


def read_score(answer) -> dict:
    """The probability-weighted level and the nearest level's description."""
    level = int(answer.score + 0.5)
    return {"score": answer.score, "level": level, "label": answer.legend[level], "confidence": answer.confidence}


def read_noul(answer) -> dict:
    """P(yes) with a yes / uncertain / no band. A Noul has no separate confidence."""
    value = answer.noul
    band = "yes" if value >= NOUL_YES else "no" if value <= NOUL_NO else "uncertain"
    return {"noul": value, "band": band}


def decide(state) -> dict:
    """Read every answer, then branch. Replace the return with the decision your code needs."""
    response = ask(state)
    answers = response.answers
    team = read_choice(answers["team"])
    urgent = read_noul(answers["urgent"])
    refund_requested = read_noul(answers["refund_requested"])
    # Branch on the values above here; keep every threshold as a constant at the top.
    return {
        "model": response.model,
        "team": team,
        "urgent": urgent,
        "refund_requested": refund_requested,
    }


def main(argv: list[str]) -> int:
    if len(argv) > 1:
        with (sys.stdin if argv[1] == "-" else open(argv[1], encoding="utf-8")) as handle:
            state = json.load(handle)
    else:
        state = EXAMPLE_STATE
    print(json.dumps(decide(state), ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
